/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Modelo.Cliente;
import Modelo.Destino;
import Modelo.PaqueteTuristico;
import Modelo.PaqueteTuristicoMultiple;
import Modelo.PaqueteTuristicoUnico;
import Modelo.Venta;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Duran, Ivan David Bejarano Diaz, Zuri Saday Messu, Michael Steven Reyes
 */
public class UsaGUIVenta extends javax.swing.JFrame {
    
    
    ArrayList<Venta>datosVentas;
    ArrayList<Cliente> datosClientes; 

    /**
     * Creates new form UsaGUIVenta
     */
     private static final java.util.Set<String> CIUDADES_COLOMBIA = new java.util.HashSet<>(
        java.util.Arrays.asList(
            "CALI","PASTO","IBAGUE","MEDELLIN","BOGOTA","BOGOTA D.C.","CARTAGENA",
            "BARRANQUILLA","SANTA MARTA","BUCARAMANGA","PEREIRA","MANIZALES",
            "CUCUTA","SAN ANDRES","VALLEDUPAR","NEIVA","VILLAVICENCIO","MONTERIA",
            "ARMENIA","TUNJA","POPAYAN"
        )
    );

    public UsaGUIVenta() {
        datosVentas   = new ArrayList<>();
        datosClientes = new ArrayList<>();
        initComponents();
        // Valores por defecto de checkboxes al arrancar
        jCheckBoxHotel.setSelected(true);
        jCheckBoxVuelo.setSelected(true);
        jCheckBoxAlimentacion.setSelected(true);
        jCheckBoxSoloDesayuno.setSelected(false);
        jCheckBoxAsistencia.setSelected(false);
        configurarNavegacionEnter();
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane();
        scroll.setViewportView(getContentPane());
        setContentPane(scroll);
        setSize(1100, 900);
    }

    /** Normaliza texto: quita tildes y pasa a mayúsculas para comparar ciudades */
    private String normalizarCiudad(String ciudad) {
        String s = ciudad.trim().toUpperCase();
        s = s.replace("\u00C1","A").replace("\u00C9","E").replace("\u00CD","I")
             .replace("\u00D3","O").replace("\u00DA","U").replace("\u00DC","U")
             .replace("\u00D1","N")
             .replace("\u00E1","A").replace("\u00E9","E").replace("\u00ED","I")
             .replace("\u00F3","O").replace("\u00FA","U").replace("\u00FC","U")
             .replace("\u00F1","N");
        return s;
    }

    private boolean esCiudadValida(String ciudad) {
        return CIUDADES_COLOMBIA.contains(normalizarCiudad(ciudad));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        REGISTRODEVENTA2 = new javax.swing.JPanel();
        jTextFieldNombreCliente2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jComboBoxTipoID2 = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jTextFieldNumeroID2 = new javax.swing.JTextField();
        jTextFieldTelefono2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextFieldEmail2 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextFieldNombreContacto2 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextFieldDescuento2 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jComboBoxEmpresa2 = new javax.swing.JComboBox<>();
        jTextFieldCodigoPaquete2 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jComboBoxCategoria2 = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        jTextFieldNombrePaquete2 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTextFieldTarifaDia2 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jTextFieldDias3 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextFieldUnidades2 = new javax.swing.JTextField();
        jButtonGuardarVenta2 = new javax.swing.JButton();
        jButtonLimpiar2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jCheckBoxHotel = new javax.swing.JCheckBox();
        jCheckBoxVuelo = new javax.swing.JCheckBox();
        jCheckBoxSoloDesayuno = new javax.swing.JCheckBox();
        jCheckBoxAsistencia = new javax.swing.JCheckBox();
        jCheckBoxAlimentacion = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldOrigen2 = new javax.swing.JTextField();
        jTextFieldDestino3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTipologia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonTodas = new javax.swing.JButton();
        jTextFieldNumeroVenta = new javax.swing.JTextField();
        jButtonPorNumero = new javax.swing.JButton();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButtonPorPosicion = new javax.swing.JButton();
        jButtonPorEstado = new javax.swing.JButton();
        jComboBoxPosicion = new javax.swing.JComboBox<>();
        jButtonPorCategoria = new javax.swing.JButton();
        jComboBoxCategoriaBusq = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResultados = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldNumActualizar = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPagar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jButtonGuardarVentas = new javax.swing.JButton();
        jButtonCargarVentas = new javax.swing.JButton();
        jButtonGuardarClientes = new javax.swing.JButton();
        jButtonCargarClientes = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(1100, 900));
        setResizable(false);

        REGISTRODEVENTA2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldNombreCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreClienteActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Nombre Cliente");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setText("REGISTRO DE VENTA");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Email");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("Tipo ID");

        jComboBoxTipoID2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxTipoID2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C - Cédula", "N - NIT" }));
        jComboBoxTipoID2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTipoIDMouseClicked(evt);
            }
        });
        jComboBoxTipoID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoIDActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setText("Núm.ID");

        jTextFieldNumeroID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroIDActionPerformed(evt);
            }
        });

        jTextFieldTelefono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefono2mailActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setText("Teléfono");

        jTextFieldEmail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setText("Nombre Contacto");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setText("Descuento %");

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setText("Empresa?");

        jComboBoxEmpresa2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxEmpresa2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "False", "True" }));

        jLabel47.setBackground(new java.awt.Color(204, 204, 204));
        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setText("PAQUETE TURISTICO");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel48.setText("Codigo Paquete");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setText("Categoria");

        jComboBoxCategoria2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxCategoria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Único", "Múltiple" }));
        jComboBoxCategoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setText("Nombre Paquete");

        jTextFieldNombrePaquete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombrePaqueteActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel51.setText("Origen");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel52.setText("Tarifa/ día");

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel53.setText("Destino ");

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setText("Días Permanencia");

        jTextFieldDias3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDias3ActionPerformed(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setText("Unidades");

        jTextFieldUnidades2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUnidadesActionPerformed(evt);
            }
        });

        jButtonGuardarVenta2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonGuardarVenta2.setText("GUARDAR VENTA");
        jButtonGuardarVenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarVentaActionPerformed(evt);
            }
        });

        jButtonLimpiar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLimpiar2.setText("LIMPIAR");
        jButtonLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jCheckBoxHotel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxHotel.setText("Hotel");
        jCheckBoxHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHotelActionPerformed(evt);
            }
        });

        jCheckBoxVuelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxVuelo.setText("Vuelo");

        jCheckBoxSoloDesayuno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxSoloDesayuno.setText("Solo Desayuno");

        jCheckBoxAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxAsistencia.setText("Asistencia Medica");

        jCheckBoxAlimentacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxAlimentacion.setText("Alimentación ");
        jCheckBoxAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAlimentacionActionPerformed(evt);
            }
        });

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DESCRIPCIÓN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tipología");

        javax.swing.GroupLayout REGISTRODEVENTA2Layout = new javax.swing.GroupLayout(REGISTRODEVENTA2);
        REGISTRODEVENTA2.setLayout(REGISTRODEVENTA2Layout);
        REGISTRODEVENTA2Layout.setHorizontalGroup(
            REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel39)
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel41)))
                        .addGap(18, 18, 18)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombreCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                    .addComponent(jComboBoxTipoID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel42)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNumeroID2))
                                .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                    .addComponent(jTextFieldEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel43)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addComponent(jTextFieldDescuento2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxEmpresa2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextFieldNombreContacto2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel53)
                                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel50)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                                .addComponent(jTextFieldOrigen2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTRODEVENTA2Layout.createSequentialGroup()
                                                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(171, 171, 171))
                                                    .addComponent(jTextFieldTarifaDia2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextFieldNombrePaquete2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                                    .addComponent(jTextFieldTipologia)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jCheckBoxVuelo)
                                                        .addComponent(jCheckBoxAlimentacion))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                                            .addComponent(jCheckBoxHotel)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(jCheckBoxAsistencia))
                                                        .addComponent(jCheckBoxSoloDesayuno))
                                                    .addGap(35, 35, 35))
                                                .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                                    .addComponent(jTextFieldDestino3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jTextFieldDias3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(19, 19, 19)
                                                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldUnidades2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCodigoPaquete2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel49)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                        .addComponent(jButtonGuardarVenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                        .addComponent(jButtonLimpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1))
                                .addGap(12, 12, 12))
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(138, 138, 138))))
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4)))
                .addContainerGap())
        );
        REGISTRODEVENTA2Layout.setVerticalGroup(
            REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jTextFieldNombreCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jComboBoxTipoID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(jTextFieldNumeroID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jTextFieldTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(jTextFieldEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(jTextFieldNombreContacto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel45)
                    .addComponent(jTextFieldDescuento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEmpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodigoPaquete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49)
                            .addComponent(jComboBoxCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(jTextFieldNombrePaquete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(jTextFieldTarifaDia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOrigen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(jLabel54)
                            .addComponent(jTextFieldDias3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55)
                            .addComponent(jTextFieldUnidades2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTipologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxVuelo)
                    .addComponent(jCheckBoxHotel)
                    .addComponent(jCheckBoxAsistencia))
                .addGap(6, 6, 6)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarVenta2)
                    .addComponent(jButtonLimpiar2)
                    .addComponent(jCheckBoxAlimentacion)
                    .addComponent(jCheckBoxSoloDesayuno))
                .addGap(18, 18, 18))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonTodas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonTodas.setText("TODAS");
        jButtonTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTodasActionPerformed(evt);
            }
        });

        jTextFieldNumeroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroVentaActionPerformed(evt);
            }
        });

        jButtonPorNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPorNumero.setText("POR NÚMERO");
        jButtonPorNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorNumeroActionPerformed(evt);
            }
        });

        jComboBoxEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A - Activa", "P - Pagada", "C - Cancelada" }));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });

        jButtonPorPosicion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPorPosicion.setText("POR POSICIÓN");
        jButtonPorPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorPosicionActionPerformed(evt);
            }
        });

        jButtonPorEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPorEstado.setText("POR ESTADO");
        jButtonPorEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorEstadoActionPerformed(evt);
            }
        });

        jComboBoxPosicion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxPosicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P - Primera", "U - Última" }));
        jComboBoxPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPosicionActionPerformed(evt);
            }
        });

        jButtonPorCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPorCategoria.setText("POR CATEGORIA");
        jButtonPorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorCategoriaActionPerformed(evt);
            }
        });

        jComboBoxCategoriaBusq.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxCategoriaBusq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Único", "Múltiple" }));
        jComboBoxCategoriaBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaBusqActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("RESULTADOS");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("CONSULTAS");

        jTextAreaResultados.setColumns(20);
        jTextAreaResultados.setRows(5);
        jScrollPane2.setViewportView(jTextAreaResultados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxCategoriaBusq, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButtonTodas)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonPorNumero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNumeroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButtonPorEstado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonPorPosicion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxPosicion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonPorCategoria))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(jLabel22))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTodas)
                    .addComponent(jTextFieldNumeroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPorNumero)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonPorPosicion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPorEstado)
                        .addGap(9, 9, 9)
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPorCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCategoriaBusq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("ACTUALIZAR VENTA");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("NÚM. VENTA");

        jTextFieldNumActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumActualizarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancelar.setText("CANCELAR VENTA");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPagar.setText("REGISTRAR VENTA");
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumActualizar)
                .addGap(43, 43, 43)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPagar)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldNumActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonPagar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("ARCHIVO DE OBJETOS");

        jButtonGuardarVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonGuardarVentas.setText("GUARDAR VENTAS");
        jButtonGuardarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarVentasActionPerformed(evt);
            }
        });

        jButtonCargarVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCargarVentas.setText("CARGAR VENTAS");
        jButtonCargarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarVentasActionPerformed(evt);
            }
        });

        jButtonGuardarClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonGuardarClientes.setText("GUARDAR CLIENTES");
        jButtonGuardarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarClientesActionPerformed(evt);
            }
        });

        jButtonCargarClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCargarClientes.setText("CARGAR CLIENTES");
        jButtonCargarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarClientesActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jButtonCargarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGuardarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jButtonCargarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(454, 454, 454))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarVentas)
                    .addComponent(jButtonCargarVentas)
                    .addComponent(jButtonGuardarClientes)
                    .addComponent(jButtonCargarClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(REGISTRODEVENTA2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(REGISTRODEVENTA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        // Cambiar estado de venta a PAGADA
        try {
            if (jTextFieldNumActualizar.getText().isBlank()) {
                JOptionPane.showMessageDialog(null,
                    "Ingrese el número de venta a pagar.",
                    "CAMPO VACÍO", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int numVenta = Integer.parseInt(jTextFieldNumActualizar.getText());
            boolean encontrada = false;
            for (Venta v : datosVentas) {
                if (v.getNumero() == numVenta) {
                    if (v.getEstado() == 'C') {
                        JOptionPane.showMessageDialog(null,
                            "No se puede pagar una venta cancelada.",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    v.setEstado('P');
                    v.setFechaHoraActualizacion(LocalDateTime.now());
                    encontrada = true;
                    JOptionPane.showMessageDialog(null,
                        "Venta #" + numVenta + " marcada como PAGADA.",
                        "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }
            if (!encontrada) {
                JOptionPane.showMessageDialog(null,
                    "No existe una venta con el número " + numVenta,
                    "NO ENCONTRADA", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null,
                "El número de venta debe ser un valor numérico.",
                "ERROR DE FORMATO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPagarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // Cambiar estado de venta a CANCELADA
        try {
            if (jTextFieldNumActualizar.getText().isBlank()) {
                JOptionPane.showMessageDialog(null,
                    "Ingrese el número de venta a cancelar.",
                    "CAMPO VACÍO", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int numVenta = Integer.parseInt(jTextFieldNumActualizar.getText());
            boolean encontrada = false;
            for (Venta v : datosVentas) {
                if (v.getNumero() == numVenta) {
                    if (v.getEstado() == 'P') {
                        JOptionPane.showMessageDialog(null,
                            "No se puede cancelar una venta ya pagada.",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    v.setEstado('C');
                    v.setFechaHoraActualizacion(LocalDateTime.now());
                    encontrada = true;
                    JOptionPane.showMessageDialog(null,
                        "Venta #" + numVenta + " CANCELADA exitosamente.",
                        "ÉXITO", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }
            if (!encontrada) {
                JOptionPane.showMessageDialog(null,
                    "No existe una venta con el número " + numVenta,
                    "NO ENCONTRADA", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null,
                "El número de venta debe ser un valor numérico.",
                "ERROR DE FORMATO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxCategoriaBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaBusqActionPerformed
        
    }//GEN-LAST:event_jComboBoxCategoriaBusqActionPerformed

    private void jButtonPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorCategoriaActionPerformed
        // Consultar ventas por categoría de paquete (Único o Múltiple)
        String categoriaSeleccionada = (String) jComboBoxCategoriaBusq.getSelectedItem();
        StringBuilder sb = new StringBuilder();
        sb.append("=== VENTAS CON PAQUETES ").append(categoriaSeleccionada.toUpperCase()).append(" ===\n\n");
        boolean hayResultados = false;
        for (Venta v : datosVentas) {
            for (PaqueteTuristico p : v.getSusPaquetesTuristicos()) {
                boolean esUnico    = p instanceof Modelo.PaqueteTuristicoUnico;
                boolean esMultiple = p instanceof Modelo.PaqueteTuristicoMultiple;
                if ((categoriaSeleccionada.equals("Único") && esUnico)
                 || (categoriaSeleccionada.equals("Múltiple") && esMultiple)) {
                    sb.append(formatearVenta(v));
                    hayResultados = true;
                    break;
                }
            }
        }
        if (!hayResultados) {
            sb.append("No se encontraron ventas con paquetes de categoría ")
              .append(categoriaSeleccionada).append(".");
        }
        jTextAreaResultados.setText(sb.toString());
    }//GEN-LAST:event_jButtonPorCategoriaActionPerformed

    private void jComboBoxPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPosicionActionPerformed
        
    }//GEN-LAST:event_jComboBoxPosicionActionPerformed

    private void jButtonPorEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorEstadoActionPerformed
        // Consultar ventas por estado (Activa, Pagada, Cancelada)
        String estadoSeleccionado = (String) jComboBoxEstado.getSelectedItem();
        char codigoEstado = estadoSeleccionado.charAt(0); // 'A', 'P' o 'C'
        StringBuilder sb = new StringBuilder();
        sb.append("=== VENTAS CON ESTADO: ").append(estadoSeleccionado).append(" ===\n\n");
        boolean hayResultados = false;
        for (Venta v : datosVentas) {
            if (v.getEstado() == codigoEstado) {
                sb.append(formatearVenta(v));
                hayResultados = true;
            }
        }
        if (!hayResultados) {
            sb.append("No se encontraron ventas con estado ").append(estadoSeleccionado).append(".");
        }
        jTextAreaResultados.setText(sb.toString());
    }//GEN-LAST:event_jButtonPorEstadoActionPerformed

    private void jButtonPorPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorPosicionActionPerformed
        // Consultar la primera o la última venta registrada
        String posicion = (String) jComboBoxPosicion.getSelectedItem();
        if (datosVentas.isEmpty()) {
            jTextAreaResultados.setText("No hay ventas registradas.");
            return;
        }
        Venta v;
        if (posicion.startsWith("P")) {
            v = datosVentas.get(0);
            jTextAreaResultados.setText("=== PRIMERA VENTA ===\n\n" + formatearVenta(v));
        } else {
            v = datosVentas.get(datosVentas.size() - 1);
            jTextAreaResultados.setText("=== ÚLTIMA VENTA ===\n\n" + formatearVenta(v));
        }
    }//GEN-LAST:event_jButtonPorPosicionActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // Sin acción adicional requerida
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jButtonPorNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorNumeroActionPerformed
        if (jTextFieldNumeroVenta.getText().isBlank()) {
            JOptionPane.showMessageDialog(null,
                "Ingrese el número de venta a buscar.",
                "CAMPO VACÍO", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int numeroVenta = Integer.parseInt(jTextFieldNumeroVenta.getText());
            jTextAreaResultados.setText(consultarVentaDadoNumero(datosVentas, numeroVenta));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null,
                "El número de venta debe ser un valor numérico.",
                "ERROR DE FORMATO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPorNumeroActionPerformed

    private void jTextFieldNumeroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroVentaActionPerformed
        
    }//GEN-LAST:event_jTextFieldNumeroVentaActionPerformed

    private void jButtonTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTodasActionPerformed
        jTextAreaResultados.setText(consultarTodasVentas(datosVentas));
    }//GEN-LAST:event_jButtonTodasActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldNombreCliente2.setText("");
        jTextFieldNumeroID2.setText("");
        jTextFieldEmail2.setText("");
        jTextFieldTelefono2.setText("");
        jTextFieldNombreContacto2.setText("");
        jTextFieldDescuento2.setText("");
        jTextFieldCodigoPaquete2.setText("");
        jTextFieldNombrePaquete2.setText("");
        jTextFieldOrigen2.setText("");
        jTextFieldDestino3.setText("");
        jTextFieldTarifaDia2.setText("");
        jTextFieldDias3.setText("");
        jTextFieldUnidades2.setText("");
        jTextFieldTipologia.setText("");
        jTextAreaDescripcion.setText("");
        jTextAreaResultados.setText("");
        jTextFieldNumeroVenta.setText("");
        jTextFieldNumActualizar.setText("");
        jComboBoxTipoID2.setSelectedIndex(0);
        jComboBoxEmpresa2.setSelectedIndex(0);
        jComboBoxCategoria2.setSelectedIndex(0);
        jCheckBoxHotel.setSelected(true);
        jCheckBoxVuelo.setSelected(true);
        jCheckBoxAlimentacion.setSelected(true);
        jCheckBoxSoloDesayuno.setSelected(false);
        jCheckBoxAsistencia.setSelected(false);
        jTextFieldNombreCliente2.requestFocus();
    

    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarVentaActionPerformed
        // Construir y registrar la venta a partir de los campos del formulario
                try {
            // 1. Campos obligatorios
            if (jTextFieldNombreCliente2.getText().isBlank()
             || jTextFieldNumeroID2.getText().isBlank()
             || jTextFieldCodigoPaquete2.getText().isBlank()
             || jTextFieldNombrePaquete2.getText().isBlank()
             || jTextFieldTarifaDia2.getText().isBlank()
             || jTextFieldDias3.getText().isBlank()
             || jTextFieldTipologia.getText().isBlank()) {
                JOptionPane.showMessageDialog(null,
                    "Complete todos los campos obligatorios:\n"
                    + "Nombre Cliente, Núm. ID, Código Paquete,\n"
                    + "Nombre Paquete, Tipología, Tarifa/Día y Días.",
                    "CAMPOS VACÍOS", JOptionPane.WARNING_MESSAGE);
                return;

            }
 
            // 2. Nombre del cliente — solo letras, espacios y tildes
            String nombre = jTextFieldNombreCliente2.getText().trim();
            if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ' -]{3,}")) {
                JOptionPane.showMessageDialog(null,
                    "El nombre del cliente solo puede contener letras y espacios\n"
                    + "y debe tener al menos 3 caracteres.",
                    "NOMBRE INVÁLIDO", JOptionPane.WARNING_MESSAGE);
                jTextFieldNombreCliente2.requestFocus();
                return;
            }
 
            // 3. Número de ID según tipo
            String numId = jTextFieldNumeroID2.getText().trim();
            char tipoIdValidar = jComboBoxTipoID2.getSelectedItem().toString().charAt(0);
            if (tipoIdValidar == 'N' && !numId.matches("\\d{9}")) {
                JOptionPane.showMessageDialog(null,
                    "El NIT debe tener exactamente 9 dígitos.",
                    "ID INVÁLIDO", JOptionPane.WARNING_MESSAGE);
                jTextFieldNumeroID2.requestFocus();
                return;
            } else if (tipoIdValidar == 'C' && !numId.matches("\\d{6,}")) {
                JOptionPane.showMessageDialog(null,
                    "La cédula debe tener mínimo 6 dígitos.",
                    "ID INVÁLIDO", JOptionPane.WARNING_MESSAGE);
                jTextFieldNumeroID2.requestFocus();
                return;
            }
 
            // 4. Email (opcional pero válido si se ingresa)
            String email = jTextFieldEmail2.getText().trim();
            if (!email.isEmpty() && !email.matches(
                    "^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9\\-]+(\\.[a-zA-Z0-9\\-]+)*\\.[a-zA-Z]{2,}$")) {
                JOptionPane.showMessageDialog(null,
                    "El email no tiene un formato válido.\nEjemplo: usuario@correo.com",
                    "EMAIL INVÁLIDO", JOptionPane.WARNING_MESSAGE);
                jTextFieldEmail2.requestFocus();
                return;
            }
 
            // 5. Teléfono — exactamente 10 dígitos
            String telefono = jTextFieldTelefono2.getText().trim();
            if (!telefono.matches("\\d{10}")) {
                JOptionPane.showMessageDialog(null,
                    "El teléfono debe contener exactamente 10 dígitos.\nEjemplo: 3001234567",
                    "TELÉFONO INVÁLIDO", JOptionPane.WARNING_MESSAGE);
                jTextFieldTelefono2.requestFocus();
                return;
            }
 
            // 6. Descuento — entre 0 y 70
            double descuento = 0.0;
            if (!jTextFieldDescuento2.getText().isBlank()) {
                try {
                    descuento = Double.parseDouble(jTextFieldDescuento2.getText().trim());
                    if (descuento < 0 || descuento > 70) {
                        JOptionPane.showMessageDialog(null,
                            "El descuento debe ser un valor entre 0 y 70.",
                            "DESCUENTO INVÁLIDO", JOptionPane.WARNING_MESSAGE);
                        jTextFieldDescuento2.requestFocus();
                        return;
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null,
                        "El descuento debe ser un valor numérico (ej: 10 o 10.5).",
                        "DESCUENTO INVÁLIDO", JOptionPane.WARNING_MESSAGE);
                    jTextFieldDescuento2.requestFocus();
                    return;
                }
            }
 
            // 7. Tipología
            
            String tipologia = jTextFieldTipologia.getText().trim();
            if (!tipologia.matches("[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ,. ]{3,}")) {
                JOptionPane.showMessageDialog(null,
                    "La tipología solo puede contener letras y espacios.\\n"
                    + "Ej: negocios, recreación, educativo, ecológico",
                    "TIPOLOGÍA INVÁLIDA",JOptionPane.WARNING_MESSAGE);
                jTextFieldTipologia.requestFocus(); return;
            }

            // 8. Descripción — máximo 500 caracteres, no solo números
            String descripcion = jTextAreaDescripcion.getText().trim();
            if (descripcion.length() > 500) {
                JOptionPane.showMessageDialog(null,"La descripción no puede superar 500 caracteres.\nActualmente: "+descripcion.length()+" caracteres.","DESCRIPCIÓN INVÁLIDA",JOptionPane.WARNING_MESSAGE);
                jTextAreaDescripcion.requestFocus(); return;
            }
            if (!descripcion.isEmpty() && descripcion.matches("\\d+")) {
                JOptionPane.showMessageDialog(null,"La descripción no puede contener solo números.\nDescribe el paquete con texto.","DESCRIPCIÓN INVÁLIDA",JOptionPane.WARNING_MESSAGE);
                jTextAreaDescripcion.requestFocus(); return;
            }

            // 9. Nombre paquete — mínimo 10 caracteres
            String nombrePaq = jTextFieldNombrePaquete2.getText().trim();
            if (nombrePaq.length() < 10) {
                JOptionPane.showMessageDialog(null,"El nombre del paquete debe tener mínimo 10 caracteres.","NOMBRE INVÁLIDO",JOptionPane.WARNING_MESSAGE);
                jTextFieldNombrePaquete2.requestFocus(); return;
            }

            // 10. Origen — ciudad colombiana válida
            String origen = jTextFieldOrigen2.getText().trim();
            if (!origen.isEmpty() && !esCiudadValida(origen)) {
                JOptionPane.showMessageDialog(null,
                    "El origen debe ser una ciudad colombiana válida"
                    + "Ej: Cali, Medellín, Bogotá  D.C., Cartagena, Pasto...",
                    "CIUDAD INVALIDA",JOptionPane.WARNING_MESSAGE);
                jTextFieldOrigen2.requestFocus(); return;
            }

            // 11. Destino — ciudad colombiana válida
            String nombreDest = jTextFieldDestino3.getText().trim();
            if (!nombreDest.isEmpty() && !esCiudadValida(nombreDest)) {
                JOptionPane.showMessageDialog(null,
                    "El destino debe ser una ciudad colombiana válida"
                    + "Ej: Cali, Medellín, Bogotá D.C., Cartagena, Pasto...",
                    "CIUDAD INVÁLIDA",JOptionPane.WARNING_MESSAGE);
                jTextFieldDestino3.requestFocus(); return;
            }

            // 12. Tarifa/día — entero positivo
            int tarifaDia;
            try {
                tarifaDia = Integer.parseInt(jTextFieldTarifaDia2.getText().trim());
                if (tarifaDia <= 0) throw new NumberFormatException();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null,"La tarifa por deuda debe ser un nÚmero entero positivo.","TARIFA INVÁLIDA",JOptionPane.WARNING_MESSAGE);
                jTextFieldTarifaDia2.requestFocus(); return;
            }

            // 13. Días — entre 1 y 365
            int diasDest;
            try {
                diasDest = Integer.parseInt(jTextFieldDias3.getText().trim());
                if (diasDest < 1 || diasDest > 365) throw new NumberFormatException();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null,"Los días deben ser un numero entre 1 y 365.","DÍAS INVÁLIDOS",JOptionPane.WARNING_MESSAGE);
                jTextFieldDias3.requestFocus(); return;
            }

            // 14. Unidades — entre 1 y 500
            int unidades = 1;
            if (!jTextFieldUnidades2.getText().isBlank()) {
                try {
                    unidades = Integer.parseInt(jTextFieldUnidades2.getText().trim());
                    if (unidades < 1 || unidades > 500) throw new NumberFormatException();
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null,"Las unidades deben ser un número entre 1 y 500.","UNIDADES INVÁLIDAs",JOptionPane.WARNING_MESSAGE);
                    jTextFieldUnidades2.requestFocus(); return;
                }
            }

            // 15. Validación alimentación/desayuno
            boolean alimentacion = jCheckBoxAlimentacion.isSelected();
            if (jCheckBoxSoloDesayuno.isSelected() && !alimentacion) {
                JOptionPane.showMessageDialog(null,"No puede seleccionar 'Solo Desayuno' sin marcar 'Alimentación'.","ALIMENTACIÓN INVÁLIDA",JOptionPane.WARNING_MESSAGE);
                jCheckBoxAlimentacion.requestFocus(); return;
            }
            boolean alimentacionTodo = alimentacion && !jCheckBoxSoloDesayuno.isSelected();
            boolean hotel      = jCheckBoxHotel.isSelected();
            boolean vuelo      = jCheckBoxVuelo.isSelected();
            boolean asistencia = jCheckBoxAsistencia.isSelected();

            // Construir cliente
            char    tipoId         = jComboBoxTipoID2.getSelectedItem().toString().charAt(0);
            boolean empresa        = jComboBoxEmpresa2.getSelectedItem().toString().equals("True");
            String  nombreContacto = jTextFieldNombreContacto2.getText().trim();
            String  codigoPaq      = jTextFieldCodigoPaquete2.getText().trim();
            Cliente cliente = new Cliente(tipoId, numId, empresa, nombre, email, telefono, nombreContacto, descuento);

            // Construir destino y paquete
            LinkedList<String> atractivos = new LinkedList<>();
            ArrayList<Destino> destinos   = new ArrayList<>();
            destinos.add(new Destino(nombreDest, diasDest, atractivos, false));

            String categoria = jComboBoxCategoria2.getSelectedItem().toString();
            PaqueteTuristico paquete;
            if (categoria.equals("Único")) {
                paquete = new PaqueteTuristicoUnico("Hotel General", codigoPaq, nombrePaq,
                    tipologia, descripcion, origen, destinos, alimentacionTodo, tarifaDia, unidades);
            } else {
                paquete = new PaqueteTuristicoMultiple("Sin obsequio", codigoPaq, nombrePaq,
                    tipologia, descripcion, origen, destinos, alimentacionTodo, tarifaDia, unidades);
            }
            paquete.setHotel(hotel);
            paquete.setAlimentacion(alimentacion);
            paquete.setVuelo(vuelo);
            paquete.setAsistencia(asistencia);

            ArrayList<PaqueteTuristico> paquetes = new ArrayList<>();
            paquetes.add(paquete);
            int           numVenta = generarNumeroVenta(datosVentas);
            LocalDateTime ahora    = LocalDateTime.now();
            Venta venta = new Venta(numVenta, ahora, ahora, cliente, paquetes, 'A');
            datosVentas.add(venta);

            JOptionPane.showMessageDialog(null,
                "Venta #"+numVenta+" registrada exitosamente.\nValor total a pagar: $"+venta.calcularValorTotalPagar(),
                "VENTA GUARDADA",JOptionPane.INFORMATION_MESSAGE);
            jButtonLimpiarActionPerformed(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al registrar la venta:\n"+e.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarVentaActionPerformed

    private void jTextFieldUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUnidadesActionPerformed
    }//GEN-LAST:event_jTextFieldUnidadesActionPerformed

    private void jTextFieldNombrePaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombrePaqueteActionPerformed
    }//GEN-LAST:event_jTextFieldNombrePaqueteActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jTextFieldTelefono2mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefono2mailActionPerformed
    }//GEN-LAST:event_jTextFieldTelefono2mailActionPerformed

    private void jTextFieldNumeroIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroIDActionPerformed
    }//GEN-LAST:event_jTextFieldNumeroIDActionPerformed

    private void jComboBoxTipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoIDActionPerformed
    }//GEN-LAST:event_jComboBoxTipoIDActionPerformed

    private void jComboBoxTipoIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoIDMouseClicked
    }//GEN-LAST:event_jComboBoxTipoIDMouseClicked

    private void jTextFieldNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreClienteActionPerformed
    }//GEN-LAST:event_jTextFieldNombreClienteActionPerformed

    private void jTextFieldNumActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumActualizarActionPerformed

    private void jCheckBoxHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHotelActionPerformed

    private void jCheckBoxAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAlimentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAlimentacionActionPerformed

    private void jTextFieldDias3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDias3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDias3ActionPerformed

    private void jButtonGuardarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarVentasActionPerformed
        try (java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(
                new java.io.FileOutputStream("ventas.dat"))) {
            oos.writeObject(datosVentas);
            JOptionPane.showMessageDialog(null, "Ventas guardadas correctamente.", "GUARDADO", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar ventas:\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        exportarVentasCSV();
    }//GEN-LAST:event_jButtonGuardarVentasActionPerformed

    @SuppressWarnings("unchecked")
    private void jButtonCargarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarVentasActionPerformed
        try (java.io.ObjectInputStream ois = new java.io.ObjectInputStream(
                new java.io.FileInputStream("ventas.dat"))) {
            datosVentas = (ArrayList<Venta>) ois.readObject();
            JOptionPane.showMessageDialog(null, "Ventas cargadas: " + datosVentas.size(), "CARGADO", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar ventas:\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCargarVentasActionPerformed

    private void jButtonGuardarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarClientesActionPerformed
        try (java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(
                new java.io.FileOutputStream("clientes.dat"))) {
            oos.writeObject(datosClientes);
            JOptionPane.showMessageDialog(null, "Clientes guardados correctamente.", "GUARDADO", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar clientes:\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarClientesActionPerformed

    @SuppressWarnings("unchecked")
    private void jButtonCargarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarClientesActionPerformed
        try (java.io.ObjectInputStream ois = new java.io.ObjectInputStream(
                new java.io.FileInputStream("clientes.dat"))) {
            datosClientes = (ArrayList<Cliente>) ois.readObject();
            JOptionPane.showMessageDialog(null, "Clientes cargados: " + datosClientes.size(), "CARGADO", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar clientes:\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCargarClientesActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea salir de la aplicación?", "SALIR", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * Exporta todas las ventas a un archivo CSV que puede abrirse como Excel.
     * Genera el archivo "ventas_exportadas.csv" en el directorio de trabajo.
     * agregado que se implemento para hacer lo más real posible el projecto
     */
    private void exportarVentasCSV() {
        if (datosVentas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay ventas para exportar.", "AVISO", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try (java.io.PrintWriter pw = new java.io.PrintWriter(
                new java.io.OutputStreamWriter(
                    new java.io.FileOutputStream("ventas_exportadas.csv"), java.nio.charset.StandardCharsets.UTF_8))) {
            // Encabezados
            pw.println("Num.Venta;Estado;FechaGeneracion;NombreCliente;TipoID;NumeroID;Email;Telefono;" +
                       "Empresa;Descuento%;CodigoPaquete;NombrePaquete;TipoPaquete;Tipologia;Origen;" +
                       "TarifaDia;DiasDuracion;Unidades;ValorUnidad;ValorTotalPaquete;" +
                       "ValorTotalVenta;ValorDescuento;TotalAPagar");
            for (Venta v : datosVentas) {
                Cliente c = v.getSuCliente();
                String nombreCli = c != null ? c.getNombre() : "";
                String tipoId    = c != null ? String.valueOf(c.getTipoIdentificacion()) : "";
                String numId     = c != null ? c.getNumeroIdentificacion() : "";
                String email     = c != null ? c.getEmail() : "";
                String telefono  = c != null ? c.getTelefono() : "";
                String empresa   = c != null ? (c.isEmpresa() ? "Si" : "No") : "";
                double desc      = c != null ? c.getPorcentajeDescuento() : 0;

                for (PaqueteTuristico p : v.getSusPaquetesTuristicos()) {
                    String tipoPaq = (p instanceof PaqueteTuristicoUnico) ? "Unico" : "Multiple";
                    pw.printf("%d;%s;%s;%s;%s;%s;%s;%s;%s;%.1f;%s;%s;%s;%s;%s;%d;%d;%d;%d;%d;%d;%d;%d%n",
                        v.getNumero(),
                        estadoTexto(v.getEstado()),
                        v.getFechaHoraGeneracion(),
                        nombreCli, tipoId, numId, email, telefono, empresa, desc,
                        p.getCodigo(), p.getNombre(), tipoPaq, p.getTipologiaTurismo(), p.getOrigen(),
                        p.getTarifaDia(), p.calcularDuracionTotalDias(), p.getCantidadUnidades(),
                        p.calcularValorUnidad(), p.calcularValorTotal(),
                        v.calcularValorTotalPaquetes(), v.calcularValorDescuento(), v.calcularValorTotalPagar());
                }
            }
            JOptionPane.showMessageDialog(null,
                "Exportación exitosa.\nArchivo: ventas_exportadas.csv\n" +
                "Ábralo con Excel o LibreOffice Calc.", "EXPORTADO", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al exportar:\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    // =========================================================
    //   MÉTODOS AUXILIARES (helpers)
    // =========================================================

    /** Formatea una Venta en texto legible para el area de resultados */
    public int generarNumeroVenta(ArrayList<Venta> ventas) {
        int max = 0;
        for (Venta v : ventas) {
            if (v.getNumero() > max) max = v.getNumero();
        }
        return max + 1;
    }
 /** -----
 /** -----
  */
    /** Formatea una venta completa para mostrar en el área de resultados */
    private String formatearVenta(Venta v) {
        StringBuilder sb = new StringBuilder();
        sb.append("==========================================\n");
        sb.append("N Venta           : ").append(v.getNumero()).append("\n");
        sb.append("Estado            : ").append(estadoTexto(v.getEstado())).append("\n");
        sb.append("Fecha generacion  : ").append(v.getFechaHoraGeneracion()).append("\n");
        sb.append("Ultima act.       : ").append(v.getFechaHoraActualizacion()).append("\n");
 
        if (v.getSuCliente() != null) {
            Cliente c = v.getSuCliente();
            sb.append("---- CLIENTE ----\n");
            sb.append("  Nombre     : ").append(c.getNombre()).append("\n");
            sb.append("  Tipo ID    : ").append(c.getTipoIdentificacion() == 'C' ? "Cedula" : "NIT").append("\n");
            sb.append("  Num. ID    : ").append(c.getNumeroIdentificacion()).append("\n");
            sb.append("  Email      : ").append(c.getEmail()).append("\n");
            sb.append("  Telefono   : ").append(c.getTelefono()).append("\n");
            sb.append("  Contacto   : ").append(c.getNombreContacto()).append("\n");
            sb.append("  Empresa    : ").append(c.isEmpresa() ? "Si" : "No").append("\n");
            sb.append("  Descuento  : ").append(c.getPorcentajeDescuento()).append("%\n");
        }
 
        sb.append("---- PAQUETES ----\n");
        sb.append("  Cantidad paquetes    : ").append(v.getSusPaquetesTuristicos().size()).append("\n");
        sb.append("  Total unidades       : ").append(v.calcularCantidadTotalUnidadesPaquetes()).append("\n");
        sb.append("  Valor total paquetes : $").append(v.calcularValorTotalPaquetes()).append("\n");
        sb.append("  Valor descuento      : $").append(v.calcularValorDescuento()).append("\n");
        sb.append("  TOTAL A PAGAR        : $").append(v.calcularValorTotalPagar()).append("\n");
 
        // ✅ Si la venta está cancelada NO se muestra el detalle de paquetes
        if (v.getEstado() == 'C') {
            sb.append("  (venta cancelada — detalle de paquetes no disponible)\n");
        } else {
            int idx = 1;
            for (PaqueteTuristico p : v.getSusPaquetesTuristicos()) {
                boolean esUnico = p instanceof PaqueteTuristicoUnico;
                sb.append("  -- Paquete ").append(idx++).append(" [")
                  .append(esUnico ? "Unico" : "Multiple").append("] --\n");
                sb.append("     Codigo       : ").append(p.getCodigo()).append("\n");
                sb.append("     Nombre       : ").append(p.getNombre()).append("\n");
                sb.append("     Tipologia    : ").append(p.getTipologiaTurismo()).append("\n");
                sb.append("     Origen       : ").append(p.getOrigen()).append("\n");
                sb.append("     Tarifa/dia   : $").append(p.getTarifaDia()).append("\n");
                sb.append("     Duracion     : ").append(p.calcularDuracionTotalDias()).append(" dia(s)\n");
                sb.append("     Hotel        : ").append(p.isHotel()      ? "Incluido"  : "No incluido").append("\n");
                sb.append("     Alimentacion : ").append(p.isAlimentacion()
                    ? (p.isAlimentacionTodo() ? "Todo incluido" : "Solo desayuno")
                    : "No incluida").append("\n");
                sb.append("     Vuelo        : ").append(p.isVuelo()      ? "Incluido"  : "No incluido").append("\n");
                sb.append("     Asistencia   : ").append(p.isAsistencia() ? "Incluida"  : "No incluida").append("\n");
                if (esUnico) {
                    PaqueteTuristicoUnico pu = (PaqueteTuristicoUnico) p;
                    sb.append("     Hotel nombre : ").append(pu.getNombreHotel()).append("\n");
                } else {
                    PaqueteTuristicoMultiple pm = (PaqueteTuristicoMultiple) p;
                    sb.append("     Destino ini. : ").append(pm.obtenerDestinoInicial().getNombreLugar()).append("\n");
                    sb.append("     Destino fin. : ").append(pm.obtenerDestinoFinal().getNombreLugar()).append("\n");
                    sb.append("     Obsequio     : ").append(pm.getObsequio()).append("\n");
                }
                sb.append("     Valor unidad : $").append(p.calcularValorUnidad()).append("\n");
                sb.append("     Valor total  : $").append(p.calcularValorTotal()).append("\n");
            }
        }
        return sb.toString();
    }
 
    private String estadoTexto(char estado) {
        return switch (estado) {
            case 'A' -> "Activa";
            case 'P' -> "Pagada";
            case 'C' -> "Cancelada";
            default  -> String.valueOf(estado);
        };
    }
 
    private String consultarTodasVentas(ArrayList<Venta> ventas) {
        if (ventas.isEmpty()) return "No hay ventas registradas.";
        StringBuilder sb = new StringBuilder("=== TODAS LAS VENTAS ===\n\n");
        for (Venta v : ventas) sb.append(formatearVenta(v));
        sb.append("\nTotal registradas: ").append(ventas.size());
        return sb.toString();
    }
 
    private String consultarVentaDadoNumero(ArrayList<Venta> ventas, int numero) {
        for (Venta v : ventas) {
            if (v.getNumero() == numero)
                return "=== VENTA ENCONTRADA ===\n\n" + formatearVenta(v);
        }
        return "No se encontró ninguna venta con el número " + numero + ".";
    }
 
    // =========================================================
    //   NAVEGACIÓN CON ENTER ENTRE CAMPOS
    // =========================================================
    private void configurarNavegacionEnter() {
        java.awt.event.ActionListener moverFoco = e ->
            ((java.awt.Component) e.getSource()).transferFocus();
 
        jTextFieldNombreCliente2.addActionListener(moverFoco);
        jTextFieldNumeroID2.addActionListener(moverFoco);
        jTextFieldEmail2.addActionListener(moverFoco);
        jTextFieldTelefono2.addActionListener(moverFoco);
        jTextFieldNombreContacto2.addActionListener(moverFoco);
        jTextFieldDescuento2.addActionListener(moverFoco);
        jTextFieldCodigoPaquete2.addActionListener(moverFoco);
        jTextFieldNombrePaquete2.addActionListener(moverFoco);
        jTextFieldOrigen2.addActionListener(moverFoco);
        jTextFieldTarifaDia2.addActionListener(moverFoco);
        jTextFieldDestino3.addActionListener(moverFoco);
        jTextFieldDias3.addActionListener(moverFoco);
        jTextFieldUnidades2.addActionListener(moverFoco);
        jTextFieldNumeroVenta.addActionListener(e -> jButtonPorNumeroActionPerformed(e));
        jTextFieldNumActualizar.addActionListener(moverFoco);
    }
 
    // =========================================================
    //   MAIN
    // =========================================================
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) { javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsaGUIVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new UsaGUIVenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel REGISTRODEVENTA2;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCargarClientes;
    private javax.swing.JButton jButtonCargarVentas;
    private javax.swing.JButton jButtonGuardarClientes;
    private javax.swing.JButton jButtonGuardarVenta2;
    private javax.swing.JButton jButtonGuardarVentas;
    private javax.swing.JButton jButtonLimpiar2;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JButton jButtonPorCategoria;
    private javax.swing.JButton jButtonPorEstado;
    private javax.swing.JButton jButtonPorNumero;
    private javax.swing.JButton jButtonPorPosicion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTodas;
    private javax.swing.JCheckBox jCheckBoxAlimentacion;
    private javax.swing.JCheckBox jCheckBoxAsistencia;
    private javax.swing.JCheckBox jCheckBoxHotel;
    private javax.swing.JCheckBox jCheckBoxSoloDesayuno;
    private javax.swing.JCheckBox jCheckBoxVuelo;
    private javax.swing.JComboBox<String> jComboBoxCategoria2;
    private javax.swing.JComboBox<String> jComboBoxCategoriaBusq;
    private javax.swing.JComboBox<String> jComboBoxEmpresa2;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxPosicion;
    private javax.swing.JComboBox<String> jComboBoxTipoID2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextArea jTextAreaResultados;
    private javax.swing.JTextField jTextFieldCodigoPaquete2;
    private javax.swing.JTextField jTextFieldDescuento2;
    private javax.swing.JTextField jTextFieldDestino3;
    private javax.swing.JTextField jTextFieldDias3;
    private javax.swing.JTextField jTextFieldEmail2;
    private javax.swing.JTextField jTextFieldNombreCliente2;
    private javax.swing.JTextField jTextFieldNombreContacto2;
    private javax.swing.JTextField jTextFieldNombrePaquete2;
    private javax.swing.JTextField jTextFieldNumActualizar;
    private javax.swing.JTextField jTextFieldNumeroID2;
    private javax.swing.JTextField jTextFieldNumeroVenta;
    private javax.swing.JTextField jTextFieldOrigen2;
    private javax.swing.JTextField jTextFieldTarifaDia2;
    private javax.swing.JTextField jTextFieldTelefono2;
    private javax.swing.JTextField jTextFieldTipologia;
    private javax.swing.JTextField jTextFieldUnidades2;
    // End of variables declaration//GEN-END:variables

}